
-- Criar tabela para os modelos de treino estruturados
CREATE TABLE public.workout_models (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  general_objective text NOT NULL,
  method_description text NOT NULL,
  level text NOT NULL CHECK (level IN ('Básico', 'Intermediário', 'Avançado')),
  initial_activation text NOT NULL,
  format_type text NOT NULL,
  structure_description text NOT NULL,
  sequence_description text,
  timer_enabled boolean NOT NULL DEFAULT false,
  timer_type text,
  voice_cadence_enabled boolean NOT NULL DEFAULT false,
  voice_cadence_pattern text,
  additional_observations text,
  periodization_phase text NOT NULL CHECK (periodization_phase IN ('Base', 'Intensificação', 'Realização', 'Deload')),
  week_number integer NOT NULL,
  stimulus_type text NOT NULL,
  exercise_fields jsonb DEFAULT '[]'::jsonb,
  model_order integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.workout_models ENABLE ROW LEVEL SECURITY;

-- Política para visualização (todos podem ver os modelos)
CREATE POLICY "Everyone can view workout models" 
  ON public.workout_models 
  FOR SELECT 
  USING (true);

-- Política para criação/edição (apenas usuários autenticados)
CREATE POLICY "Authenticated users can manage workout models" 
  ON public.workout_models 
  FOR ALL 
  USING (auth.role() = 'authenticated');

-- Inserir os 50 modelos de treino estruturados
INSERT INTO public.workout_models (
  name, general_objective, method_description, level, initial_activation,
  format_type, structure_description, sequence_description, timer_enabled, timer_type,
  voice_cadence_enabled, voice_cadence_pattern, additional_observations,
  periodization_phase, week_number, stimulus_type, model_order
) VALUES 
-- FASE BASE - Semana 1
('Explosão em 30 Segundos', 
 'Estímulo metabólico e gasto calórico com explosão muscular sob curta duração.',
 'HIIT – 30s ON / 30s OFF – 4 rodadas.',
 'Intermediário',
 'Mobilidade articular + aquecimento dinâmico.',
 'HIIT',
 '6 exercícios em 4 rodadas.',
 'Alternar partes do corpo.',
 true, '30s ON / 30s OFF',
 true, '1:0:1',
 'Controle de esforço individual.',
 'Base', 1, 'HIIT', 1),

('Missão Corpo Blindado',
 'Força e estabilidade corporal total com foco técnico.',
 'Bi-sets com núcleo ativo (força + core).',
 'Intermediário',
 'Mobilidade escápulo-pélvica + isometria abdominal.',
 'Bi-set',
 '4 blocos de 2 exercícios, 3 séries cada.',
 NULL,
 true, 'Pausa de 90s',
 true, '2:1:2',
 'Priorizar técnica sobre carga.',
 'Base', 1, 'Força Técnica', 2),

('Dominância Posterior',
 'Focar na cadeia posterior e na estabilidade pélvica.',
 'Força isolada e unilateral com isometria.',
 'Intermediário',
 'Mobilidade de quadril e ativação de glúteos.',
 'Séries diretas',
 '5 exercícios, 3 séries de 10 repetições com pausa de 30s.',
 NULL,
 true, 'Pausa de 30s',
 true, '2:1:1',
 'Foco na contração do músculo-alvo.',
 'Base', 1, 'Força', 3),

-- FASE BASE - Semana 2
('Zona de Impacto Corporal',
 'Condicionamento com foco em tempo sob tensão total.',
 'EMOM (Every Minute On the Minute) por 12 minutos.',
 'Intermediário',
 'Mobilidade geral + pré-ativação do core.',
 'EMOM',
 '12 minutos (3 exercícios x 4 rodadas).',
 'Min 1: Inferior / Min 2: Superior / Min 3: Core.',
 true, 'EMOM 12 min',
 true, '2:0:1',
 'Regular intensidade com tempo de execução.',
 'Base', 2, 'EMOM', 4),

('Combustão Piramidal',
 'Resistência e controle sob fadiga com escadas de volume.',
 'Pirâmide crescente/decrescente de repetições (6-8-10-8-6).',
 'Intermediário',
 'Mobilidade de tornozelo/quadril + técnica de movimento.',
 'Pirâmide',
 '3 blocos de 3 exercícios cada.',
 NULL,
 true, 'Pausa de 30s entre exercícios',
 true, '2:1:1',
 'Ideal para transição ou progressão.',
 'Base', 2, 'Pirâmide', 5),

('Duelo Metabólico',
 'Aceleração do metabolismo com superséries em contraste.',
 'Supersérie entre cardio e força funcional.',
 'Avançado',
 'Sequência cíclica + ativação do core.',
 'Superset',
 '3 superséries, 4 blocos, sem pausa entre os pares.',
 NULL,
 true, '45s por exercício',
 true, '1:1:1',
 'Exige controle de respiração e foco.',
 'Base', 2, 'Superset', 6),

('Circuito Inverso',
 'Trabalhar intensidade no início e técnica ao final do treino.',
 'Circuito com repetições decrescentes.',
 'Intermediário',
 'Aquecimento geral e revisão técnica dos movimentos.',
 'Circuito Decrescente',
 '6 exercícios com repetições em 20-15-10.',
 NULL,
 true, 'Livre com pausas controladas',
 true, '2:0:1',
 'Manter a qualidade do movimento mesmo com a queda das repetições.',
 'Base', 2, 'Resistência', 7),

('Metabólico Alternado',
 'Trabalhar potência metabólica com estímulos diversos.',
 'Alternância entre cardio e força leve.',
 'Intermediário',
 'Mobilidade e ativação cardio leve.',
 'Circuito alternado',
 '3 blocos com 2 exercícios cada, 4 rodadas.',
 NULL,
 true, '40s ON / 20s OFF',
 true, '1:0:1',
 'Foco na transição rápida entre os exercícios.',
 'Base', 2, 'Resistência Metabólica', 8),

-- FASE BASE - Semana 3
('Cardio Precision',
 'Resistência cardiovascular com controle de ritmo e técnica.',
 'Intervalado com tempo fixo e controle respiratório.',
 'Básico',
 'Marcha, mobilidade torácica e coordenação rítmica.',
 'Intervalado',
 'Bloco contínuo de 20 minutos.',
 '40s de execução (ON) / 20s de pausa (OFF).',
 true, '40s ON / 20s OFF x 10 (ou mais)',
 true, '1:0:1',
 'Adaptável para bike, elíptico, escada.',
 'Base', 3, 'Cardio Técnico', 9),

('Círculo de Potência',
 'Coordenação, potência e transição rápida entre estímulos.',
 'Circuito balístico com foco em pliometria e movimento atlético.',
 'Avançado',
 'Ativação de quadríceps e reatividade (pulos e sprint leve).',
 'Circuito',
 '5 exercícios, 3 rodadas.',
 '30s por exercício, 1 minuto de pausa entre rodadas.',
 true, '30s ON / 30s OFF',
 false, 'Explosivo',
 'Foco total em execução com potência máxima.',
 'Base', 3, 'Potência', 10),

('Tabata Tática',
 'Intensidade curta com foco técnico e fadiga localizada.',
 '4 blocos no formato Tabata (20s ON / 10s OFF x 8).',
 'Intermediário',
 'Coordenação geral + pré-treino específico do bloco.',
 'Tabata',
 '4 blocos (Core, Inferior, Superior, Funcional).',
 NULL,
 true, 'Tabata 20s/10s x 8',
 true, '2:0:2',
 'Pode ser usado como treino curto ou complemento.',
 'Base', 3, 'Estímulo Intervalado Curto', 11),

('Conexão Total',
 'Integrar membros superiores e inferiores com foco em coordenação e sinergia muscular.',
 'Circuito funcional cruzado (empurrar, puxar, agachar, estabilizar).',
 'Intermediário',
 'Mobilidade torácica, quadril e tornozelos + padrão de empurrar/puxar leve.',
 'Circuito',
 '6 exercícios, 3 rodadas.',
 '40s de execução / 20s de transição.',
 true, '40s ON / 20s OFF',
 true, '2:0:1',
 'Ideal para aulas em grupo ou circuito técnico.',
 'Base', 3, 'Coordenação Total', 12),

('Ladeira Acima',
 'Construir resistência muscular localizada e tolerância à fadiga.',
 'Ladders (escada de repetições): 5-10-15-10-5 reps.',
 'Avançado',
 'Mobilidade + ativação isolada dos grupos-alvo.',
 'Ladder (Escada)',
 '3 exercícios por bloco.',
 'Pausa de 30s entre os estágios da escada.',
 true, 'Cronômetro livre com beep de estágio',
 true, '2:1:1',
 'Incentivar controle de movimento mesmo nas séries curtas.',
 'Base', 3, 'Escada Muscular', 13),

('Pulso Ativo',
 'Elevar a frequência cardíaca com foco em agilidade e deslocamentos.',
 'Treino em circuito com deslocamentos, pliometria e cardio técnico.',
 'Intermediário',
 'Ativação cardio leve, saltos coordenados e mobilidade dinâmica.',
 'Circuito',
 '8 exercícios, 3 rodadas.',
 '30s de execução + 15s de descanso.',
 true, '30s ON / 15s OFF',
 true, '1:0:1',
 'Ajustável para treinos outdoor ou indoor.',
 'Base', 3, 'Agilidade/Cardio', 14),

('Núcleo em Ação',
 'Reforçar a estabilidade central com controle isométrico e dinâmico.',
 'Treino específico para CORE com variação de planos e bases.',
 'Básico',
 'Mobilidade de coluna e ativação glúteo/abdominal.',
 'Séries diretas',
 '5 exercícios, 3 séries cada.',
 '40s de execução / 20s de descanso.',
 true, '40s ON / 20s OFF',
 true, '3:0:3',
 'Ideal como treino autônomo ou complemento.',
 'Base', 3, 'Estabilidade', 15),

('Central de Potência',
 'Ativação máxima do core e membros inferiores.',
 'Pliometria + isometria de base estável.',
 'Intermediário',
 'Mobilidade de quadril, ativação de core e saltos leves.',
 'Circuito',
 '5 exercícios, 3 rounds.',
 '45s de execução / 15s de pausa.',
 true, '45s ON / 15s OFF',
 true, '2:0:1',
 'Focar na aterrissagem controlada nos saltos.',
 'Base', 3, 'Potência', 16);

-- Continuar com os demais modelos...
INSERT INTO public.workout_models (
  name, general_objective, method_description, level, initial_activation,
  format_type, structure_description, sequence_description, timer_enabled, timer_type,
  voice_cadence_enabled, voice_cadence_pattern, additional_observations,
  periodization_phase, week_number, stimulus_type, model_order
) VALUES 
-- FASE BASE - Semana 4
('Resistência de Aço',
 'Estimular força e resistência em blocos com tempo sob tensão (TUT) alto.',
 'Foco em repetições longas e contínuas por 60 segundos.',
 'Avançado',
 'Mobilidade e séries com elástico ou peso corporal.',
 'Time Under Tension (TUT)',
 '3 blocos com 2 exercícios cada.',
 'Cada exercício por 60s contínuos, com 30s de pausa entre blocos.',
 true, '60s execução / 30s pausa',
 true, '4:1:2',
 'Controle técnico essencial no final do tempo.',
 'Base', 4, 'Resistência', 17),

('Complexo de Movimento',
 'Executar padrões combinados que envolvem múltiplas articulações.',
 'Complexos com halteres, barras ou peso corporal (ex: agachar + empurrar + puxar).',
 'Avançado',
 'Mobilidade específica e padrão técnico com carga leve.',
 'Complexos',
 '4 complexos (sequência de 3 movimentos), 3 séries cada.',
 '5 a 6 repetições por combinação.',
 true, 'Tempo livre com beep a cada série',
 true, '2:0:2',
 'Ideal para treinos com sobrecarga moderada.',
 'Base', 4, 'Padrões Combinados', 18),

('Sprint Tático',
 'Estimular potência anaeróbica e aceleração.',
 'Blocos de corrida curta, pliometria e pausa ativa.',
 'Avançado',
 'Skipping, deslocamentos curtos, mobilidade dinâmica.',
 'Blocos combinados',
 '4 blocos (Sprint + Pliometria + Isometria), 3 séries por bloco.',
 NULL,
 true, '20s execução / 40s pausa',
 false, 'Explosivo',
 'Ideal para treinos outdoor ou em quadra.',
 'Base', 4, 'Velocidade e Reação', 19),

-- FASE INTENSIFICAÇÃO - Semana 5
('Força no Limite',
 'Aumento de força com carga progressiva e intervalo longo.',
 'Cluster sets com carga alta e pausa ativa.',
 'Avançado',
 'Mobilização ativa + série técnica com 50% da carga.',
 'Cluster Set',
 '4 blocos com séries de 4x4 repetições.',
 'Pausa interna de 15s entre as 4 repetições.',
 true, 'Cluster 4x4 com pausas internas',
 true, '3:0:1',
 'Ideal para dias de baixo volume e foco neural.',
 'Intensificação', 5, 'Força Máxima', 20),

('Carga Inteligente',
 'Hipertrofia com manipulação de cadência e volume reduzido.',
 'Treino com slow tempo (cadência lenta) e foco em amplitude total.',
 'Intermediário',
 'Mobilidade articular + ativação muscular isolada.',
 'Séries com Cadência Lenta',
 '3 blocos de 3 exercícios, 3 séries cada.',
 NULL,
 true, 'Tempo livre por série',
 true, '4:1:2',
 'Excelente para dias de carga moderada com máximo controle.',
 'Intensificação', 6, 'Hipertrofia Isolada', 21),

('Tempo Controlado',
 'Fortalecer musculatura com foco técnico e controle de tempo (TUT).',
 'Cadência lenta com exercícios isolados e compostos.',
 'Intermediário',
 'Mobilidade passiva + ativação leve do grupo trabalhado.',
 'Cadência Lenta (TUT)',
 '3 blocos de 2 exercícios cada.',
 'Cadência 5:1:3.',
 true, 'Controle de tempo por bloco',
 true, '5:1:3',
 'Ideal para objetivo estético ou controle técnico.',
 'Intensificação', 5, 'Hipertrofia Controlada', 22),

('Estabiliza e Ataca',
 'Alternar estabilidade (isometria) e explosão (pliometria).',
 'Combinação de isometria e exercícios balísticos.',
 'Intermediário',
 'Core isométrico + técnica de salto + pré-ativação de glúteos.',
 'Duplas Isométrico/Balístico',
 '5 duplas de exercícios, 3 rodadas.',
 '30s cada exercício da dupla.',
 true, '30s:30s por dupla',
 true, '2:0:1',
 'Equilíbrio e foco na desaceleração.',
 'Intensificação', 5, 'Explosão com Estabilidade', 23),

('Resistência em Blocos',
 'Desenvolver resistência geral e mental com variação de tempo.',
 'Blocos de 4 minutos com estímulo contínuo.',
 'Intermediário',
 'Aquecimento global + simulação de movimentos do treino.',
 'Blocos de Esforço',
 '3 blocos de 4 minutos cada, com 3 exercícios rotativos.',
 '1 min de descanso entre os blocos.',
 true, '4 min ON / 1 min OFF',
 true, '2:0:1',
 'Foco em não parar durante o bloco de esforço.',
 'Intensificação', 5, 'Resistência Muscular', 24);

-- Continuar com o restante dos modelos... (devido ao limite de caracteres, vou adicionar os demais em uma segunda inserção)
